FROM node:16-alpine

WORKDIR /usr

COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm ci

ENV PORT 3001

EXPOSE 3001

RUN npm run build

ENTRYPOINT ["npm", "run", "start"]
